Added Dutch translation
chzesa/ftt pull request #1
Opened 2021-05-25 12:30 UTC by Vistaus

🙂

2021-05-27 20:06 UTC, chzesa commented
Thank you for your contribution. While it'd be perfectly ok to merge as is, I'm afraid I'd forgotten to use internationalization for a context menu entry. I've now also added the options page strings to messages.json.
If you can add translations for these new strings I'll hold off on merging this.

2021-05-30 10:04 UTC, Vistaus commented
Done! 🙂

2021-05-30 12:56 UTC, chzesa requested changes

2021-05-30 12:56 UTC, chzesa commented on src/_locales/nl/messages.json
> +}
The closing brace on line 104 causes a parsing error.

2021-05-30 15:11 UTC, Vistaus commented on src/_locales/nl/messages.json
> +}
Good catch! I just fixed it. I blame GNOME's Meld for this error 😒

2021-05-30 17:09 UTC, merged